# Generated by Django 4.2.11 on 2024-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_name_seller_username_alter_seller_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
